### ISSUE TITLE
Initial set-up. "cannot compile unless --modules flag is specified'

### ISSUE THREAD

**Issue by ghost** [DeborahK/AngularU2015-Angular2Forms#1]
I forked this project and cloned it to my laptop. When I opened the project in visual studio code,the app.ts file is asking me to specify --module flag so the modules can be loaded. 
Initially i thought it was because the reference path is not given and I had included this line of code.
" /// reference path ="typings/angular2/angular2" /"
where do I need to specify the modules flag? 

![image](https://cloud.githubusercontent.com/assets/11040896/8362607/9367e120-1b97-11e5-9510-27a24a929c2f.png)

**Comment by DeborahK** [comment]
Yes, I get this too when I first open up the project. As soon as I do a build, all of the errors go away. Have you tried Ctrl+Shift+B to build it?

**Comment by ghost** [comment]
Yeah,it went away. Now I have a problem in running it. After I built it,I ran the run task. But when go to the browser I don't see anything. The other day at angularu,you had run it magically. Do I need to change any setting?

**Comment by DeborahK** [comment]
I was using the code directly from the repository, so there shouldn't be any other setting/code changes that you need to make. I'm not sure what you mean by "run task"?

Here are the steps I used to actually run an application using Visual Studio Code:
1) At the command prompt type: npm install -g http-server.
2) At the command prompt: Change to the directory containing the index.html file.
3) At the comment prompt type: http-server. This should run the server needed to launch the application.
4) In the browser (I was able to use IE or Chrome) type: http://localhost:8080/index.html

Let me know if that works for you.

**Comment by ghost** [comment]
yes.. it worked..so far I had been running from  the folder-AngularU2015-Angular2Forms. Now that I went into sampleapp folder and started the http-server,it is working well. Thanks for the wonderful session! btw,I loved your Angular session on pluralsight too - "angular front to back with web api".

**Comment by DeborahK** [comment]
Glad you got it working!
Thank you so much for the kind words about the AngularU session and my Pluralsight course!
At this point, I am closing this issue.
Thanks again!
